plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'maven-publish'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

publishing {
    publications {
        fabric(MavenPublication) {
            artifactId = "${mod_id}-fabric"

            artifact(remapJar) {
                builtBy remapJar
            }

            artifact(sourcesJar)

            pom {
                name = "${mod_name} Fabric"
                description = project.description ?: "Fabric version of ${mod_name}"
                url = "https://github.com/xun39/armoryapi"

                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/license/mit/'
                    }
                }

                developers {
                    developer {
                        id = 'Xun'
                        name = 'Xun'
                    }
                }

                scm {
                    connection = 'scm:git:git://github.com/xun39/armoryapi.git'
                    developerConnection = 'scm:git:ssh://github.com:xun39/armoryapi.git'
                    url = 'https://github.com/xun39/armoryapi'
                }
            }
        }
    }
}
